// <auto-generated />
using System;
using GPRC.persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GPRC.persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210228235940_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GPRC.core.domaine.Entities.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_effet_premier_paiement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_entree_jouissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_mise_en_sommeil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag_majoration_rente")
                        .HasColumnType("bit");

                    b.Property<int>("Num_as400")
                        .HasColumnType("int");

                    b.Property<int>("Numero_dossier")
                        .HasColumnType("int");

                    b.Property<string>("Zone_libre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dossier");
                });
#pragma warning restore 612, 618
        }
    }
}
